/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package expression

import kotlin.test.Test
import kotlin.test.assertTrue

class ExpTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val exp = Exp()
        assertTrue(exp.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
