/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package expression

class Exp {
    fun someLibraryMethod(): Boolean {
        return true
    }
}

fun main() {
    val exp = Exp()
    exp.someLibraryMethod()
}
